name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Nim ${{ matrix.nim }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim: [2.2.0, 2.2.2, 2.2.4] #, devel]
    steps:
    - uses: actions/checkout@v4
    - uses: jiro4989/setup-nim-action@v2
      with:
        nim-version: ${{ matrix.nim }}
        use-nightlies: true
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup
      run: |
        nimble install -y --depsOnly
    - name: Run Tests
      run: |
        nimble test
